variables:
  POSTGRES_DATABASE: fd_database
  POSTGRES_USER: fd_user
  POSTGRES_PASSWORD: fd_password

stages:
  - deploy

default:
  image: ubuntu:20.04
  services:
    - postgres:12.10

deploy:
  stage: deploy
  script:
    - apt -y update
    - apt -y install apt-utils
    - apt -y install net-tools python3 python3-pip mysql-client libmysqlclient-dev
    - apt -y upgrade
    - python3 back/manage.py makemigrations
    - python3 back/manage.py migrate
    - python3 back/manage.py check
  only:
    - main

