variables:
  POSTGRES_DB: fd_database
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

stages:
  - deploy

default:
  image: ubuntu:20.04
  services:
    - postgres:12.10

deploy:
  stage: deploy
  script:
    - apt -y update
    - apt -y install apt-utils
    - DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt -y install tzdata
    - apt -y install net-tools python3 python3-pip postgresql postgresql-contrib libpq-dev
    - apt -y upgrade
    - cd back
    - python3 -m pip install psycopg2
    - python3 -m pip install Django
    - service postgresql restart
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py check
  only:
    - main

