variables:
  POSTGRES_DATABASE: fd_database
  POSTGRES_USER: fd_user
  POSTGRES_PASSWORD: fd_password

stages:
  - deploy

default:
  image: ubuntu:20.04
  services:
    - postgres:12.10

deploy:
  stage: deploy
  script:
    - apt -y update
    - apt -y install apt-utils
    - DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt -y install tzdata
    - apt -y install net-tools python3 python3-pip postgresql postgresql-contrib libpq-dev
    - apt -y upgrade
    - cd back
    - python3 -m pip install psycopg2
    - python3 -m pip install Django
    - service postgresql restart
    
    - -u postgres createdb $DATABASE_NAME -e
    - -u postgres psql -d $DATABASE_NAME -c "create user fd_user with encrypted password 'fd_password';"
    - -u postgres psql -d $DATABASE_NAME -c "grant all privileges on database $DATABASE_NAME to fd_user;"
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py check
  only:
    - main

