cache:
  untracked: true

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - apt -y update
    - apt -y upgrade
    - apt -y install python3 python3-pip postgresql postgresql-contrib libpq-dev
    - service postgresql restart
    - python3 -m pip install psycopg2
    - python3 -m pip install Django
    - ls /etc/postgresql
    - ls /var/lib/pgsql/data/
 
    - sed -i 's/peer/trust/g' /etc/postgresql/12/main/pg_hba.conf
    - sed -i 's/md5/trust/g' /etc/postgresql/12/main/pg_hba.conf
    - service postgresql restart
    - psql -U postgres -d template1 -c "ALTER USER postgres PASSWORD 'fd_admin';"
    - export PGPASSWORD=fd_admin
    - sed -i 's/trust/md5/g' /etc/postgresql/12/main/pg_hba.conf
    - service postgresql restart

    - createdb -U postgres -h localhost fd_database
    - psql -d  fd_database -c "create user fd_user with encrypted password 'fd_password';"
    - psql -d fd_database -c "grant all privileges on database $DATABASE_NAME to fd_user;"
  only:
    - main

deploy:
  stage: deploy
  script:
    - python3 front/manage.py makemigrations
    - python3 front/manage.py migrate
  only:
    - main
  dependencies:
    - build
