image: python:3.8.10

services:
  - postgres:12.10
variables:
  POSTGRES_DB: fd_database
  POSTGRES_USER: fd_user
  POSTGRES_PASSWORD: "fd_password"
  POSTGRES_HOST_AUTH_METHOD: trust

build:
  script:
    - apt -y update
    - apt -y install apt-utils
    - DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt -y install tzdata
    - apt -y install net-tools python3 python3-pip postgresql postgresql-contrib libpq-dev
    - apt -y upgrade
    - python3 -m pip install psycopg2
    - python3 -m pip install Django
    - service postgresql restart
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
    - python3 back/manage.py makemigrations
    - python3 back/manage.py migrate
    - python3 back/manage.py check
