stages:
  - build
  - deploy

build:
  stage: build
  services:
    - postgres:12.10
  variables:
    POSTGRES_DB: fd_database
    POSTGRES_USER: fd_user
    POSTGRES_PASSWORD: fd_password
  script:
    - apt -y update
    - apt -y upgrade
    - apt -y install python3 python3-pip postgresql postgresql-contrib libpq-dev
    - service postgresql start
    - python3 -m pip install psycopg2
    - python3 -m pip install Django
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

  only:
    - main

deploy:
  stage: deploy
  script:
    - python3 front/manage.py makemigrations
    - python3 front/manage.py migrate
  only:
    - main
  dependencies:
    - build
