# Generated by Django 4.0.4 on 2022-05-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0002_alter_article_price_alter_menu_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
